name: Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
  
  
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '17.0'
        include-prerelease: true

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    # Install vcpkg dependencies
    - name: Install vcpkg dependencies
      run: |
        cd vcpkg
        .\vcpkg install zydis:x86-windows zydis:x64-windows
        .\vcpkg integrate install

    # Build the Ichigo and Shinigami projects
    - name: Build the Ichigo and Shinigami projects
      run: |
        cd Shinigami
        msbuild Shinigami.sln /t:Ichigo`;Shinigami /p:Configuration=Release /p:Platform=x64
        msbuild Shinigami.sln /t:Ichigo`;Shinigami /p:Configuration=Release /p:Platform=x86

    - name: Create Release and Zip Binaries
      run: |
        mkdir release
        Compress-Archive -LiteralPath Release/ -DestinationPath release/Shinigami-x86.zip 
        Compress-Archive -LiteralPath x64/Release -DestinationPath release/Shinigami-x64.zip 

    # Upload release artifacts
    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Shinigami and Ichigo Binaries
        path: release
