name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
    steps:
    - uses: actions/checkout@v2

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    # Install vcpkg dependencies
    - name: Install vcpkg dependencies
      run: |
        cd vcpkg
        .\vcpkg install zydis:${{ matrix.platform }}-windows

    # Build the Ichigo and Shinigami projects
    - name: Build the Ichigo and Shinigami projects
      run: |
        cd Shinigami
        msbuild Shinigami.sln /t:Ichigo;Shinigami /p:Configuration=Release /p:Platform=${{ matrix.platform }}
